language: minimal

addons:
  apt:
      packages:
      - fakeroot
      - maven
      - rpm

os:
  - linux
  - osx
  - windows

before_script:
  - if [ ! -z $TRAVIS_TAG ]; then
    echo "tag set -> set version to tag version";
    export CORREO_VERSION=`echo $TRAVIS_TAG | cut -d "v" -f 2`;
    else export CORREO_VERSION=99.99.99;
    fi
  - echo "CORREO_VERSION is $CORREO_VERSION"

jobs:
  allow_failures:
    - os: windows
  include:
    - stage: build
      os: linux
      script:
        - .travis/setup_linux.bash
        - .travis/build_plugins.bash
        - .travis/build_correo.bash
        - .travis/package_linux.bash
      before_deploy:
        - cd target
      deploy:
        provider: releases
        api_key: '$GITHUB_API_KEY'
        file_glob: true
        file: 
          - "*.deb"
          - "*.rpm"
        skip_cleanup: true
        on:
          tags: true  
    - stage: build
      os: osx
      script:
        - .travis/setup_osx.bash
        - .travis/build_plugins.bash
        - .travis/build_correo.bash
        - .travis/package_osx.bash
      before_deploy:
        - cd target
      deploy:
        provider: releases
        api_key: '$GITHUB_API_KEY'
        file_glob: true
        file: 
          - "*.dmg"
        skip_cleanup: true
        on:
          tags: true
    - stage: build
      os: windows
      script:
        - .travis/setup_window.bash
        - .travis/build_plugins.bash
        - .travis/build_correo.bash
        - .travis/package_windows.bash