language: minimal

addons:
  apt:
      packages:
      - fakeroot
      - maven
      - rpm

os:
  - linux
  - osx
  - windows

jobs:
  allow_failures:
    - os: windows
  include:
    - stage: build
      os: linux
      script:
        - .travis/build.bash linux
      before_deploy:
        - cd target
      deploy:
        provider: releases
        api_key: '$GITHUB_API_KEY'
        file_glob: true
        file: 
          - "*.deb"
          - "*.rpm"
        skip_cleanup: true
        on:
          tags: true  
    - stage: build
      os: osx
      script:
        - .travis/build.bash osx
      before_deploy:
        - cd target
      deploy:
        provider: releases
        api_key: '$GITHUB_API_KEY'
        file_glob: true
        file: 
          - "*.dmg"
        skip_cleanup: true
        on:
          tags: true
    - stage: build
      os: windows
      script:
        - .travis/build.bash windows
      deploy:
        provider: releases
        api_key: '$GITHUB_API_KEY'
        file_glob: true
        file:
          - "*.msi"
        skip_cleanup: true
        on:
          tags: true