[package]
name = "correo-app"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
build = "build.rs"

[[bin]]
name = "correomqtt"
path = "src/main.rs"

[dependencies]
correo-core = { path = "../correo-core" }
correo-diagnostics = { path = "../correo-diagnostics" }
correo-mqtt = { path = "../correo-mqtt" }
correo-plugins = { path = "../correo-plugins" }
correo-plugins-systopic = { path = "../../plugins/correo-plugins-systopic" }
correo-storage = { path = "../correo-storage" }
correo-ui = { path = "../correo-ui" }
rfd.workspace = true
eframe.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
rumqttd = { version = "0.20", default-features = false }
semver.workspace = true
sha2.workspace = true
tokio.workspace = true
tracing.workspace = true
ureq.workspace = true
zip.workspace = true

[build-dependencies]
serde_json.workspace = true
toml.workspace = true

[lints]
workspace = true
