name: Release CI
on:
  release:
    types: [published]
  workflow_dispatch:
jobs:
  linuxbuild:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configure GPG Key
        run: |
          echo -n "$GPG_PRIVATE_KEY" | base64 --decode | gpg2 --import
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
      - name: Build
        run: .github/build.bash linux
        id: build
        shell: bash
      - name: Release 
        uses: xresloader/upload-to-github-release@v1.3.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          draft: false
          file: target/*.deb;target/*.rpm
          tags: true
  winbuild:
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: .github/build.bash windows
        id: build
        shell: bash
      - name: Release 
        uses: xresloader/upload-to-github-release@v1.3.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          draft: false
          file: target/*.msi
          tags: true
  macbuild:
    runs-on: macos-11
    steps:    
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: .github/build.bash osx
        id: build
        shell: bash
      - name: Release 
        uses: xresloader/upload-to-github-release@v1.3.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          draft: false
          file: target/*.dmg
          tags: true
