name: Release CI
on:
  release:
    types: [published]
  workflow_dispatch:
jobs:
  linuxbuild:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v2
      - run: .github/build.bash linux
        shell: bash
  winbuild:
    runs-on: windows-2019
    steps:
      - name: Checkout master
        uses: actions/checkout@v2
      - run: .github/build.bash windows
        shell: bash
  macbuild:
    runs-on: macos-11
    steps:    
      - name: Checkout master
        uses: actions/checkout@v2
      - run: .github/build.bash osx
        shell: bash
