name: Release CI
on:
  release:
    types: [published]
  workflow_dispatch:
jobs:
  linuxbuild:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v2
      - run: .github/build.bash linux
        id: build
        shell: bash
      - name: Release Artifacts
        uses: Roang-zero1/github-upload-release-artifacts-action@master
        with:
          args: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  winbuild:
    runs-on: windows-2019
    steps:
      - name: Checkout master
        uses: actions/checkout@v2
      - run: .github/build.bash windows
        id: build
        shell: bash
      - name: Release Artifacts
        uses: Roang-zero1/github-upload-release-artifacts-action@master
        with:
          args: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  macbuild:
    runs-on: macos-11
    steps:    
      - name: Checkout master
        uses: actions/checkout@v2
      - run: .github/build.bash osx
        id: build
        shell: bash
      - name: Release Artifacts
        uses: Roang-zero1/github-upload-release-artifacts-action@master
        with:
          args: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
